# Generated by Django 5.1.2 on 2024-10-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('activity_type', models.CharField(max_length=255, null=True)),
                ('activity_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'activity_logs',
            },
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('official_site_url', models.CharField(max_length=255, null=True)),
                ('hashtags', models.TextField(null=True)),
                ('comments', models.TextField(null=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('entry_fee', models.CharField(max_length=255, null=True)),
                ('introduction', models.TextField(null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('search_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'festivals',
            },
        ),
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_key', models.CharField(max_length=255, null=True, unique=True)),
                ('setting_value', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'global_settings',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(max_length=255, null=True)),
                ('stat_value', models.IntegerField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'statistics',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
