# Generated by Django 5.1.2 on 2024-10-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='festival',
            name='hashtags',
        ),
        migrations.RemoveField(
            model_name='festival',
            name='rating',
        ),
        migrations.AddField(
            model_name='festival',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='entry_fee',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='official_site_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='search_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='view_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
