# Generated by Django 5.1.2 on 2024-11-15 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chatlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'verbose_name': 'Activity Log', 'verbose_name_plural': 'Activity Logs'},
        ),
        migrations.AlterModelOptions(
            name='chatlog',
            options={'verbose_name': 'Chat Log', 'verbose_name_plural': 'Chat Logs'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='festival',
            options={'verbose_name': 'Festival', 'verbose_name_plural': 'Festivals'},
        ),
        migrations.AlterModelOptions(
            name='globalsetting',
            options={'verbose_name': 'Global Setting', 'verbose_name_plural': 'Global Settings'},
        ),
        migrations.AlterModelOptions(
            name='hashtag',
            options={'verbose_name': 'Hashtag', 'verbose_name_plural': 'Hashtags'},
        ),
        migrations.AlterModelOptions(
            name='statistic',
            options={'verbose_name': 'Statistic', 'verbose_name_plural': 'Statistics'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_time',
            field=models.DateTimeField(auto_now_add=True, help_text='활동 발생 시간'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(blank=True, help_text='활동 유형 (예: 로그인)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='description',
            field=models.TextField(blank=True, help_text='활동에 대한 설명', null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user_id',
            field=models.IntegerField(blank=True, help_text='활동을 수행한 사용자 ID', null=True),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='chatbot_response',
            field=models.TextField(help_text='챗봇이 생성한 응답 텍스트'),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='로그가 생성된 시간'),
        ),
        migrations.AlterField(
            model_name='chatlog',
            name='user_input',
            field=models.TextField(help_text='사용자가 입력한 텍스트'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(help_text='댓글 내용'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='festa',
            field=models.ForeignKey(help_text='댓글이 작성된 축제', on_delete=django.db.models.deletion.CASCADE, to='api.festival'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(help_text='사용자 평점'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='title',
            field=models.CharField(help_text='댓글 제목', max_length=255),
        ),
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(help_text='사용자 이름', max_length=255),
        ),
        migrations.AlterField(
            model_name='festival',
            name='address',
            field=models.CharField(blank=True, help_text='축제 장소 주소', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='end_date',
            field=models.DateField(help_text='축제 종료 날짜'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='entry_fee',
            field=models.CharField(blank=True, help_text='입장료 정보', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='imageUrl',
            field=models.CharField(blank=True, help_text='축제 이미지 URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='intro_image1',
            field=models.CharField(blank=True, help_text='축제 소개 이미지 URL 1', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='intro_image2',
            field=models.CharField(blank=True, help_text='축제 소개 이미지 URL 2', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='intro_image3',
            field=models.CharField(blank=True, help_text='축제 소개 이미지 URL 3', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='introduction',
            field=models.TextField(blank=True, help_text='축제 소개', null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='official_site_url',
            field=models.CharField(blank=True, help_text='축제 공식 사이트 URL', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='search_count',
            field=models.IntegerField(blank=True, default=0, help_text='축제 검색 횟수', null=True),
        ),
        migrations.AlterField(
            model_name='festival',
            name='start_date',
            field=models.DateField(help_text='축제 시작 날짜'),
        ),
        migrations.AlterField(
            model_name='festival',
            name='title',
            field=models.CharField(help_text='축제 제목', max_length=255),
        ),
        migrations.AlterField(
            model_name='festival',
            name='view_count',
            field=models.IntegerField(blank=True, default=0, help_text='축제 조회수', null=True),
        ),
        migrations.AlterField(
            model_name='globalsetting',
            name='setting_key',
            field=models.CharField(blank=True, help_text='설정 키', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='globalsetting',
            name='setting_value',
            field=models.CharField(blank=True, help_text='설정 값', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='festa',
            field=models.ForeignKey(help_text='해시태그가 연결된 축제', on_delete=django.db.models.deletion.CASCADE, to='api.festival'),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='tag',
            field=models.CharField(help_text='해시태그 내용', max_length=100),
        ),
        migrations.AlterField(
            model_name='hashtag',
            name='title',
            field=models.CharField(help_text='해시태그 제목', max_length=255),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='stat_type',
            field=models.CharField(blank=True, help_text='통계 유형 (예: 사용자 수)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='stat_value',
            field=models.IntegerField(default=0, help_text='통계 값'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='마지막 업데이트 시간'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(help_text='생년월일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(help_text='사용자 이메일 주소', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], help_text='성별 (M: 남성, F: 여성)', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='사용자 실명', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='사용자 비밀번호 (암호화된 상태로 저장)', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='고유한 사용자 이름', max_length=50, unique=True),
        ),
    ]
