name: Build and deploy Django app to Azure Web App - backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'  # backend 디렉터리 내 변경 사항에 대해서만 실행
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r backend/requirements.txt  # 경로 수정

      - name: Create .env file
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> backend/.env
          echo "DEBUG=False" >> backend/.env
          echo "ALLOWED_HOSTS=backend-hnbte6c6gqaxfuh9.koreacentral-01.azurewebsites.net,.azurewebsites.net" >> backend/.env
          echo "PROD_API_URL=https://backend-hnbte6c6gqaxfuh9.koreacentral-01.azurewebsites.net" >> backend/.env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> backend/.env
          echo "DB_USER=${{ secrets.DB_USER }}" >> backend/.env
          echo "DB_PASSWORD=${{ secrets.AZURE_DB_PASSWORD }}" >> backend/.env
          echo "DB_HOST=teamdatabase.mysql.database.azure.com" >> backend/.env
          echo "DB_PORT=3306" >> backend/.env
          echo "DEFAULT_DB_NAME=default_db" >> backend/.env
          echo "FESTIVAL_DB_NAME=festival_db" >> backend/.env
          echo "USER_DB_NAME=user_db" >> backend/.env
          echo "CORS_ALLOWED_ORIGINS=https://mango-forest-0aeaf0e00.5.azurestaticapps.net" >> backend/.env
          echo "CSRF_TRUSTED_ORIGINS=https://mango-forest-0aeaf0e00.5.azurestaticapps.net,https://backend-hnbte6c6gqaxfuh9.koreacentral-01.azurewebsites.net" >> backend/.env
          echo "DJANGO_SETTINGS_MODULE=config.settings.production" >> backend/.env

      - name: Zip artifact for deployment
        run: zip -r release.zip backend -x '*.git*' -x 'venv/*'  # backend 폴더만 압축

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: django-app
          path: |
            release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: django-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_BACKEND }}  # 백엔드용으로 생성된 Secret 사용

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'backend'
          package: './backend'  # backend 폴더 배포

      - name: Delay for stability
        run: sleep 30  # 30초 대기
