name: Build and deploy Django app to Azure Web App - backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'  # backend 디렉터리 내 변경 사항에 대해서만 실행
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 코드 체크아웃
      - uses: actions/checkout@v4

      # Python 환경 설정
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # 가상 환경 생성 및 활성화
      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      # 의존성 설치
      - name: Install dependencies
        run: pip install -r backend/requirements.txt

      # 배포를 위한 압축 파일 생성
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      # 빌드된 아티팩트 업로드
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # 빌드된 아티팩트 다운로드
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # Azure 로그인
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}
          client-secret: ${{ secrets.AZUREAPPSERVICE_CLIENT_SECRET }}

      # 압축 해제
      - name: Unzip artifact for deployment
        run: unzip release.zip

      # Azure Web App에 배포
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'backend'  # Azure App Service 이름
          package: 'release.zip'  # 배포할 압축 파일
